export * from './Header/Header';
export * from './movies/MovieInfo/MovieInfo';
export * from './movies/MoviesList/MoviesList';
export * from './UserInfo/UserInfo';
export * from './movies/MoviesListCard/MoviesListCard';
export * from './Trends/Trends';
export * from './GenreInfoMovie/GenreInfoMovie.module.css';
export * from './stuff/Tvplayer'
export * from './stuff/player'